#!bash
usage="$(basename "$0") -h | -c CommitMessage -- program to apply changes to github

where:
    -h  show this help text
    -c  set the commit's message"

if [ "$1" == "-h" ] || [ "$1" == "" ]; then
  echo "Usage: $usage"
  exit 0
fi
if [ "$1" == "-c" ]; then
	if [ "$2" == "" ]; then
  		echo "Usage: $usage"
  		exit 0
	fi
	git add .
	git commit -m "$2"
	git push -u origin master
fi
